name: ipa-immune
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip>=20.2.3
  - pip:
      - cycler==0.11.0
      - htseq==0.9.1
      - joblib==1.1.1
      - matplotlib==2.0.2
      - numpy==1.19.5
      - pandas==0.20.3
      - progress==1.3
      - pybedtools==0.7.10
      - pyfasta==0.5.2
      - pyparsing==3.0.7
      - pysam==0.22.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - threadpoolctl==3.1.0